### ISSUE TITLE
NameError: global name 'codon' is not defined

### ISSUE THREAD

**Issue by juliaphilipp** [ajw2329/splice_lib#4]
Hi Andrew,
I was running cds_insertions and ran into the following error:

> splice_lib.pyc in translate_seq(seq)
>      63     for i in codon_gen(seq):
>      64 
> ---> 65         amino_acid = codon_table.get(codon, '*')
>      66         if amino_acid != '*':
>      67 
> 
> NameError: global name 'codon' is not defined

I think it's just a matter of changing "codon" to "i" in line 65 of splice_lib.py (I changed it in my copy and it all worked like a charm)

Cheers,
Julia

**Comment by ajw2329** [comment]
Fixed it - thanks very much for letting me know!! Let me know if you need anything else! (Also, will get the other things done soon - sorry for the delays!)
